import { db, stationsTable, type Station } from "@workspace/db";

const snapshotDate = new Date("2026-08-17T08:00:00.000Z");

const seedStations: Station[] = [
  {
    id: "galp-lisboa-aeroporto",
    name: "GALP Lisboa Aeroporto",
    brand: "GALP",
    city: "Lisboa",
    municipality: "Lisboa",
    district: "Lisboa",
    address: "Av. de Berlim, 12",
    latitude: 38.7756,
    longitude: -9.1296,
    petrolPrice: 1.779,
    dieselPrice: 1.689,
    evPricePerKwh: 0.42,
    evPowerKw: 150,
    open24Hours: true,
    amenities: ["Loja", "Café", "Lavagem"],
    updatedAt: snapshotDate,
  },
  {
    id: "prio-sacavem",
    name: "PRIO Sacavém",
    brand: "PRIO",
    city: "Sacavém",
    municipality: "Loures",
    district: "Lisboa",
    address: "Rua Estado da Índia, 6",
    latitude: 38.7923,
    longitude: -9.1026,
    petrolPrice: 1.689,
    dieselPrice: 1.579,
    evPricePerKwh: 0.39,
    evPowerKw: 120,
    open24Hours: false,
    amenities: ["Loja", "AdBlue"],
    updatedAt: snapshotDate,
  },
  {
    id: "bp-oeiras",
    name: "BP Oeiras Parque",
    brand: "BP",
    city: "Oeiras",
    municipality: "Oeiras",
    district: "Lisboa",
    address: "Estrada da Ribeira da Lage, 4",
    latitude: 38.7013,
    longitude: -9.3092,
    petrolPrice: 1.799,
    dieselPrice: 1.709,
    evPricePerKwh: 0.49,
    evPowerKw: 150,
    open24Hours: true,
    amenities: ["Loja", "Café", "WC"],
    updatedAt: snapshotDate,
  },
  {
    id: "repsol-matosinhos",
    name: "REPSOL Matosinhos Sul",
    brand: "REPSOL",
    city: "Matosinhos",
    municipality: "Matosinhos",
    district: "Porto",
    address: "Av. da República, 845",
    latitude: 41.1782,
    longitude: -8.689,
    petrolPrice: 1.749,
    dieselPrice: 1.659,
    evPricePerKwh: 0.45,
    evPowerKw: 180,
    open24Hours: true,
    amenities: ["Loja", "Café", "Lavagem"],
    updatedAt: snapshotDate,
  },
  {
    id: "prio-vila-nova-de-gaia",
    name: "PRIO Vila Nova de Gaia",
    brand: "PRIO",
    city: "Vila Nova de Gaia",
    municipality: "Vila Nova de Gaia",
    district: "Porto",
    address: "Rua do Canidelo, 209",
    latitude: 41.1165,
    longitude: -8.631,
    petrolPrice: 1.679,
    dieselPrice: 1.569,
    evPricePerKwh: 0.39,
    evPowerKw: 120,
    open24Hours: false,
    amenities: ["Loja", "AdBlue"],
    updatedAt: snapshotDate,
  },
  {
    id: "galp-porto-boavista",
    name: "GALP Porto Boavista",
    brand: "GALP",
    city: "Porto",
    municipality: "Porto",
    district: "Porto",
    address: "Av. da Boavista, 1100",
    latitude: 41.1579,
    longitude: -8.6427,
    petrolPrice: 1.789,
    dieselPrice: 1.699,
    evPricePerKwh: 0.44,
    evPowerKw: 150,
    open24Hours: true,
    amenities: ["Loja", "Café", "WC"],
    updatedAt: snapshotDate,
  },
  {
    id: "intermarche-coimbra",
    name: "Intermarché Coimbra",
    brand: "Intermarché",
    city: "Coimbra",
    municipality: "Coimbra",
    district: "Coimbra",
    address: "Rua António Augusto Gonçalves, 22",
    latitude: 40.2033,
    longitude: -8.4103,
    petrolPrice: 1.649,
    dieselPrice: 1.549,
    evPricePerKwh: 0.36,
    evPowerKw: 100,
    open24Hours: false,
    amenities: ["Supermercado", "Loja", "WC"],
    updatedAt: snapshotDate,
  },
  {
    id: "prio-faro",
    name: "PRIO Faro",
    brand: "PRIO",
    city: "Faro",
    municipality: "Faro",
    district: "Faro",
    address: "Estrada de São Luís, 88",
    latitude: 37.0244,
    longitude: -7.9346,
    petrolPrice: 1.719,
    dieselPrice: 1.619,
    evPricePerKwh: 0.39,
    evPowerKw: 120,
    open24Hours: true,
    amenities: ["Loja", "AdBlue", "WC"],
    updatedAt: snapshotDate,
  },
  {
    id: "auchan-braga",
    name: "Auchan Braga",
    brand: "Auchan",
    city: "Braga",
    municipality: "Braga",
    district: "Braga",
    address: "Av. Robert Smith, 101",
    latitude: 41.5482,
    longitude: -8.4265,
    petrolPrice: 1.639,
    dieselPrice: 1.539,
    evPricePerKwh: 0.35,
    evPowerKw: 100,
    open24Hours: false,
    amenities: ["Supermercado", "Loja", "Lavagem"],
    updatedAt: snapshotDate,
  },
  {
    id: "bp-evora",
    name: "BP Évora Norte",
    brand: "BP",
    city: "Évora",
    municipality: "Évora",
    district: "Évora",
    address: "Estrada de Arraiolos, km 2",
    latitude: 38.5851,
    longitude: -7.9071,
    petrolPrice: 1.739,
    dieselPrice: 1.639,
    evPricePerKwh: 0.41,
    evPowerKw: 100,
    open24Hours: true,
    amenities: ["Loja", "Café", "WC"],
    updatedAt: snapshotDate,
  },
  {
    id: "prio-setubal",
    name: "PRIO Setúbal",
    brand: "PRIO",
    city: "Setúbal",
    municipality: "Setúbal",
    district: "Setúbal",
    address: "Av. Bento de Jesus Caraça, 40",
    latitude: 38.5244,
    longitude: -8.8882,
    petrolPrice: 1.659,
    dieselPrice: 1.559,
    evPricePerKwh: 0.38,
    evPowerKw: 120,
    open24Hours: false,
    amenities: ["Loja", "AdBlue"],
    updatedAt: snapshotDate,
  },
  {
    id: "repsol-leiria",
    name: "REPSOL Leiria Centro",
    brand: "REPSOL",
    city: "Leiria",
    municipality: "Leiria",
    district: "Leiria",
    address: "Rua Paulo VI, 16",
    latitude: 39.7444,
    longitude: -8.8071,
    petrolPrice: 1.689,
    dieselPrice: 1.589,
    evPricePerKwh: 0.4,
    evPowerKw: 150,
    open24Hours: true,
    amenities: ["Loja", "Café", "Lavagem"],
    updatedAt: snapshotDate,
  },
];

let seedPromise: Promise<void> | undefined;

export async function ensureStationsSeeded(): Promise<void> {
  seedPromise ??= (async () => {
    const existing = await db
      .select({ id: stationsTable.id })
      .from(stationsTable)
      .limit(1);

    if (existing.length === 0) {
      await db.insert(stationsTable).values(seedStations);
    }
  })();

  await seedPromise;
}

export function stationSeedCount(): number {
  return seedStations.length;
}

export type StationRow = Station;